version: '3'

services:
  php:
    build:
      context: docker/php
      args:
        USER_ID: 1000
    working_dir: /app
    volumes:
      - php_extensions:/usr/local/lib/php/extensions
      - ~/.composer-docker/cache:/var/www/.composer/cache:delegated
      - ./:/app
    environment:
      PHP_USER_ID: 1000
    restart: ${RESTART}

  nginx:
    image: nginx:1.15-alpine
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
    depends_on:
      - php
    restart: ${RESTART}
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:${DOCKER_DOMAIN}"
    ports:
     - ${DOCKER_PORT}
    networks:
      - default
      - web

volumes:
  php_extensions:

networks:
  web:
    external: true
